version: 1
disable_existing_loggers: true
formatters:
  standard:
    format: '%(asctime)s:%(name)s:%(lineno)d:%(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: backend_py.log
    maxBytes: 1048576 # 1MB
    backupCount: 3
    encoding: utf8
root:
  level: INFO
  handlers: [console, file]